// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umptwnqzgredrbgqgvdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcHR3bnF6Z3JlZHJiZ3FndmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTg2ODcsImV4cCI6MjA2OTQ3NDY4N30.O0meInH1noC1f3tSjKj3VC0H97KRdd0ee3slMw2onEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});